# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "ahci"
    "usbhid"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [
    "nvidia"
    "nvidia_modeset"
    "nvidia_uvm"
    "nvidia_drm"
  ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/7d834644-3bfa-43b8-a8e7-8b2464fca1df";
    fsType = "btrfs";
    options = [
      "rw"
      "relatime"
      "ssd"
      "subvol=@nixos"
      "compress=zstd:5"
      "discard=async"
      "space_cache=v2"
    ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/7d834644-3bfa-43b8-a8e7-8b2464fca1df";
    fsType = "btrfs";
    options = [
      "rw"
      "relatime"
      "ssd"
      "subvol=@nixos_boot"
      "compress=no"
      "discard=async"
      "space_cache=v2"
    ];
  };

  fileSystems."/efi" = {
    device = "/dev/disk/by-uuid/0245-E198";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  fileSystems."/games" = {
    device = "/dev/disk/by-uuid/7d834644-3bfa-43b8-a8e7-8b2464fca1df";
    fsType = "btrfs";
    options = [
      "rw"
      "relatime"
      "ssd"
      "subvol=@games"
      "compress=zstd:5"
      "discard=async"
      "space_cache=v2"
    ];
  };

  fileSystems."/games2" = {
    device = "/dev/disk/by-uuid/1ed7e655-91d7-4458-b051-c74617410a36";
    fsType = "btrfs";
    options = [
      "rw"
      "relatime"
      "ssd"
      "subvol=@games"
      "compress=zstd:5"
      "discard=async"
      "space_cache=v2"
    ];
  };

  fileSystems."/hdd" = {
    device = "/dev/disk/by-uuid/cbb84132-656f-4a3a-981d-3fde88d396b4";
    fsType = "btrfs";
    options = [
      "noauto"
      "rw"
      "relatime"
      "subvol=@"
      "compress=zstd:5"
      "space_cache=v2"
    ];
  };

  swapDevices = [
    {
      device = "/dev/disk/by-uuid/0f9e564b-3903-4095-a503-821fffc9729b";
    }
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp111s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
